
```{r load data methods, warning = F, message = F, echo = F}
supp_correlation <- readRDS(here::here("manuscript","objects","method_correlation.rds"))
supp_prediction <- readRDS(here::here("manuscript","objects","method_prediction.rds"))
supp_lower_asym <- readRDS(here::here("manuscript","objects","lower_asym.rds"))
loo_models <- readRDS(here::here("manuscript","objects","loo_models.rds"))
load(here::here("manuscript","objects","demo.RData"))
```

## Study Design

The study employed a single-session, cross-sectional design where participants completed three tasks aimed at assessing thermal sensitivity (detection and pain thresholding), paradoxical heat sensation (PHS), and spatial aspects of thermal perception. In addition, all participants completed survey measures related to handedness, mental health, and pain sensitivity. The experiment took place at the Aarhus University Hospital, Aarhus, Denmark, and was approved by the Region Midtjylland Ethics Committee and adhered to the current version of the Declaration of Helsinki (2013). Participants provided informed consent prior to their participation in the study and were compensated for their participation. This paper focuses on a specific subset of these data, related to the effect of age on PHS which was pre-registered before data analyses. 


## Participants and Recruitment Criteria

Inclusion criteria required all participants to be between 20 and 80 years old, with no evidence of neuropathy or pain conditions, and fluent in Danish and/or English. Exclusion criteria included a diagnosed neuropathic or clinical pain condition, a known neurological or psychiatric disorder, pregnancy or lactation, recent jet lag or sleep deprivation, skin diseases such as eczema or psoriasis, a history of alcohol or drug abuse, cannabis use within the previous four weeks, and alcohol consumption within the previous 48 hours. Participants were also excluded for having a condition that may interfere with the study goals (e.g. cognitive decline or a physical disability) or that required them to take medication that is known to affect physiological pathways for either temperature or pain perception. To ensure balanced representation across the adult lifespan, participants were allocated into four age groups: 20-35; 36-50; 51-65; 66-80, where we aimed to recruit between 15 and 25 participants per group.   

A total of 84 healthy individuals took part in the study. During data screening, nine participants were excluded due to medication use (e.g., antihypertensive medications). Although these individuals self-identified as physically healthy, such medications may influence physiological responses relevant to temperature perception. Therefore, data from 75 participants (`r gen_F` F, mean age = `r age$mean`, range = `r age$min`–`r age$max`) were included in the final analyses (see Supplementary Materials for clarification of final numbers).


## Apparatus

All stimuli were delivered using a T11 Thermal Contact Stimulator (QST.Lab, Strasbourg, France), with a total stimulation surface of 90 $mm^2$ and five independently controlled stimulation zones (one zone 7.4 x 24.2 mm) and were applied to the non-dominant forearm. For each trial two neighbouring stimulation zones, chosen randomly, were either heated or cooled while the remaining three zones were maintained at a predetermined baseline temperature. All experimental tasks were coded in MATLAB R2021a, and presented using Psychtoolbox 3 [@brainard_psychophysics_1997; @kleiner_whats_2007].

## Questionnaires

The short-form of the Edinburgh Handedness Inventory (EHI, [@oldfield_assessment_1971; @veale_edinburgh_2014] was used to infer participant handedness. Participants then completed a series of questionnaires to assess pain sensitivity, pain experience in their daily life and mental health factors. Specifically, the State-Trait Inventory for Cognitive and Somatic Anxiety (STICSA), both the current and the general versions [@ree_statetrait_2000], the Pain Sensitivity Questionnaire (PSQ, [@ruscheweyh_pain_2009]), the Michigan Neuropathy Screening Instrument (MNSI, [@feldman_practical_1994]) to screen for probable peripheral neuropathy, as well we to gather information on their pain experience and pain sensitivity. Finally, the Patient Health Questionnaire (PHQ-9, [@kroenke_phq-9_2001]) was used as a brief measure of mental health status.


## Detection and Pain Thresholding

Thermal sensitivity was assessed with four brief computerised tasks designed to measure the participants’ ability to detect cooling and warming, as well as their sensitivity to painful cold and heat. These tasks were always performed after the end of the surveys and in the same order: cold detection followed by warm detection on the non-dominant volar forearm, then cold pain followed by heat pain on the dominant volar forearm. For the purposes of this study, only warm detection and heat pain thresholding were used to inform stimulus parameters, therefore we only report on those specific procedures.

A single threshold trial consisted of 1-3 s of stimulation (jittered) with the thermal probe at baseline temperature (30 ºC). After which, the two active stimulation zones increased in temperature at a rate of 2.5°C/s and were maintained at target temperature for 1.5 s. After the 1.5 s plateau, participants were asked “Was the stimulus warm?” for warm detection, or “Was the stimulus burning?” for heat pain, and used the left and right arrow keys to respond either “yes” or “no”. After the response, the active zones decreased back to baseline temperature at a rate of 80 ºC/s during which the participant’s chosen response was displayed for 0.5 s. For all tasks, participants had a maximum of 10 s to respond to each question, using the left and right arrow keys (left - “yes”, right - “no”). The warm detection task consisted of 30 trials and lasted 5 to 7 minutes. The heat pain thresholding task consisted of 50 trials, and was completed within 10 to 15 minutes. 

Detection and pain perception psychometric functions (PF) were assessed using the psi method, implemented in the Palamedes toolbox [@prins_applying_2018]. Psi is a Bayesian adaptive algorithm that iteratively updates a posterior probability distribution of the threshold and slope of a PF, allowing optimal stimulus placement for threshold and slope estimations [@courtin_assessing_2020]. This approach ensures that stimulus intensities were calibrated to individual sensitivity, limiting the number of trials at uninformative (never or always detected) or excessively painful intensities. As a result, it reduces the number of trials needed to attain a given level of estimation precision and the risk of habituation or sensitisation. Full details of the psi procedure and adaptive thresholding stimulus selection are available [here](https://doi.org/10.17605/OSF.IO/DVZ94). 

Out of the 50 trials used to assess pain sensitivity, the first 10 were familiarisation trials, where the intensity was set using an up-down staircase algorithm rather than psi. This ensured that the participant had some time to stabilise their strategy regarding what they reported as burning. These familiarisation trials were not included in the analyses. The extracted thresholds and slopes for warm detection and heat pain were then used to determine four possible peak temperatures during the PHS task.

## PHS Stimuli

To elicit PHS, we used an adapted version of the Thermal Sensory Limen (TSL) task [@mitchell_thermal_2024; @schaldemose_it_2023], in which the peak temperature for each trial was fixed and individually determined based on thermal detection and pain thresholds. The response temperature for each trial was defined as the point at which participants reported a change in perception whilst the probe temperature was decreasing from baseline (Fig. 1). 
The peak temperature for each trial was set to one of four temperature intensities, generating four levels (I-1, I-2, N-1, N-2) derived from individual warm detection and heat pain PFs (Fig. 1A). I-1 corresponds to the warm detection threshold (WDT), defined as the temperature at which there is a 50% probability of detecting warmth; I-2 is the WDT plus three times the inverse of the slope of the PF. N-1 is the heat pain threshold (HPT), defined as 50% probability of detecting heat pain; and N-2 corresponds to the HPT plus two times the inverse slope. 
The range of possible peak temperatures was bounded between 33ºC and 50ºC to ensure safe and consistent stimulation. If the calculated values for I-1 and N-4 fell outside this range, they were adjusted to either 33ºC or 49.9ºC, respectively. For participants with shallow slopes, which lead to extreme differences between contrast conditions, an upper bound of 1.5 was used for the inverse slope. If it was not possible to define four discrete and increasing temperatures within these constraints, a default set of temperatures (34, 37, 44 and 45ºC) was used to generate contrast levels. Figure 1B shows the chosen peak temperatures for each participant.
For half of the trials the probe decreased in temperature almost immediately after reaching peak temperature, whilst for the other half peak temperature was maintained at 1.5 s before the probe decreased back to baseline. 

## PHS Task

Each trial began with the thermal probe increasing in temperature, at a rate of 2.5°C/sec, from baseline (32°C) to one of four peak temperatures, followed by a decrease at the same rate back to baseline. Once the probe reached baseline temperature, a tone was played to indicate that participants could respond. The probe then remained at baseline temperature for a short interval (jittered between 0.01 and 0.5 s) to decouple the alerting effects of the tone with the following temperature change. After which, the probe temperature decreased or increased at a slower rate of 1°C/sec, to allow for more precise detection of a perceptual change (Fig. 1C). Participants could only respond once the probe temperature departed from baseline. As soon as they detected a change in sensation, the participants pressed the up arrow key, which triggered the probe to return to baseline temperature.
Immediately after their response a question appeared asking whether the perceived change in sensation was cold or warm. Participants responded using either the left or right arrow keys (counterbalanced across participants), and the response time between reporting a change in sensation and responding to the question was recorded. Next, participants rated their confidence in their chosen thermal quality using a VAS ranging from from “Guess” (coded as 0) to “Certain” (coded as 100). They used the left and right arrow keys to move the slider along the VAS scale, and pressed the up arrow key to confirm their confidence rating. Participants had 10 seconds to respond to each question (Fig. 1D).
The task had 64 trials in total, with 16 trials per contrast condition, and lasted between 20 to 30 minutes. Each condition included 14 experimental ‘PHS’ trials, where the probe temperature continued to decrease after the tone, and two ‘catch’ trials, where the probe temperature increased after the tone. The addition of catch trials was to reduce the likelihood of participants inferring that the probe temperature was always below baseline during the critical portion of the task. Prior to the main task, participants completed eight practice trials, delivered to the same location on the non-dominant forearm. 
At the end of the task, participants were asked to reflect on their detection strategy and report whether they were more likely to report a change in sensation only when they were confident of their perceived thermal quality (i.e., definitely warm or definitely cold), or whether they reported changes even when they were uncertain of the temperature quality (reported in Supplementary Materials). 

## Statistical analyses

Statistical analyses and visualisations were performed using Rstan [@team_stan_nodate] in R [@team_r_2023] and followed the planned pre-registration (2nd April 2024, [doi.org/10.17605/OSF.IO/T5NMD](doi.org/10.17605/OSF.IO/T5NMD)). All data and code for this project are publicly available on GitHub [https://github.com/Body-Pain-Perception-Lab/uncertainty-lifespan-phs](https://github.com/Body-Pain-Perception-Lab/uncertainty-lifespan-phs) and OSF [https://osf.io/wxhcq](https://osf.io/wxhcq/). 

### Data filtering

Prior to any analyses, we implemented several control checks to ensure data quality. We aimed to exclude participants with a Michigan Neuropathy Screening Instrument (MNSI, [@feldman_practical_1994; @herman_use_2012] score larger or equal to seven were excluded, as this is indicative of a possible undiagnosed peripheral neuropathy. No participants had an MSNI score of above 7. 
At the trial-level, additional data filtering was carried out to ensure that participants adhered to  task instructions. Responses were excluded if either the choice or confidence response times was less than 0.25 s, as this latency is deemed too quick to reflect deliberate decision-making processes. If the detection response time was below 0.25 s then the entire trial was removed, as it is likely that the participant was reacting to the tone and not responding to a perceived change in temperature. Finally, trials with missed choice responses (> 10 s) were also removed from analysis. 

Peak temperature conditions included data from trials where the peak temperature duration was both 0 and 1.5 s, as any analysis of these trials was not included in the pre-registration. In addition, For our main analysis we excluded all “catch” trials, where the probe temperature increased after the tone. 

We used the "catch" trial responses to infer whether our assumptions about lapse rates for the experimental trials are correct. Across all subjects, we found no significant correlation between the total number of wrongly reported catch trials and the number of reported PHS trials ($\rho$ = `r rd(supp_correlation$mean,2)` (95% HDI [`r round(supp_correlation$q5,2)`, `r round(supp_correlation$q95,2)`]), *p* = `r rd(supp_correlation$prop_above_0,2)`), suggesting that reporting errors are not associated with a higher number of PHS trials. A Bayesian mixed effects logistic regression showed that the conditional probability of an incorrect response (responding “cold”) on a “catch” trial was `r round(supp_prediction$mean[2],2) * 100`% (95 HDI [`r round(supp_prediction$q5[2],2) * 100`, `r round(supp_prediction$q95[2],2) * 100`]) which was compatible with the group level estimates of the lower asymptote of psychometric function for non-catch trials which was `r round(supp_lower_asym$mean,2)`% (95% HDI [`r round(supp_lower_asym$q5,2)`, `r round(supp_lower_asym$q95,2)`]). The very low lapse rate for "catch" trials is indicative of a low lapse rate throughout the entire experiment.

## Multivariate modelling of PHS, choice response time and confidence

Thermal contrast was defined as the normalised temperature contrast scaled by the maximum possible temperature difference (E.q. 1). Thermal contrast was then used to inform a logistic psychometric function, defined by four parameters (Eq. 2): the threshold ($\alpha_{phs}$), slope ($\beta_{phs}$), guess rate ($\gamma_{phs}$) and lapse rate ($\lambda_{phs}$). This psychometric curve estimates the latent probability of PHS ($p_{phs}$) as a function of thermal contrast (TC) for every participant. 

Equation 1:

$$
TC_i = \frac{T_{\text{warm},i} - T_{\text{cold},i}}{T_{\text{warm,max}} - T_{\text{cold,min}}}
$$

Equation 2:

$$
p_{phs_i} = \gamma_{phs} + (1 - \gamma_{phs} - \lambda_{phs}) \left( \frac{1}{1 + e^{-\beta_{phs} \cdot(TC_i - \alpha_{phs})}} \right)
$$


To further categorise the perceptual decision making of the PHS experience, we included response times and confidence ratings into the same model. This inclusion of additional behavioural responses quantified important aspects of the PHS experience that would be missed by only looking at the binary responses. Using all three behavioural measures we developed two multivariate models, based around two possible PHS profiles (true perceiver and unsure perceiver), with the main difference of how uncertainty about the PHS experience is affecting the response times and confidence ratings (Fig. 3). We assume that conditions that consistently lead to longer response times and lower reported confidence are suggestive of a greater uncertainty in choosing between “cold” and “warm”. This pattern can be used to determine whether specific stimulus conditions contribute to more ambiguous sensory experiences typically associated with PHS. 

### Model 1: True perceiver

The true perceiver assumes that perceptual uncertainty in PHS arises from the difficulty of making a categorical choice between “cold” and “warm”, rather than from the experience of PHS itself. We refer to this profile as the true perceiver, because certainty is highest at the points at which the sensation is either clearly cold, or clearly warm (i.e., PHS as a seemingly veridical warm sensation). Therefore, this model predicts the fastest response times and highest confidence at thermal contrast values where participants either feel veridical cold or report PHS with near certainty. In contrast, this model predicts the slowest response times and lowest confidence at thermal contrast values associated with 50% probability of experiencing a PHS, where the stimulus is most ambiguous. This pattern aligns with the concept of a “true” PHS responder as an individual who experiences a clear and definite warm sensation in response to a cold stimulus.

For the true perceiver model we quantify uncertainty as Shannon entropy of the probability of responding PHS (Eq. S1.1), which is linked to decision difficulty. We map the Shannon entropy to both response time and confidence ratings as affine functions.
	

### Model 2: Unsure perceiver

The unsure perceiver assumes that perceptual uncertainty in PHS arises not from the difficulty of making a categorical choice between “cold” and “warm”, but from the aberrant and unusual experience of PHS, therefore uncertainty increases with the probability of experiencing PHS itself. This profile is called the unsure perceiver as participants are more uncertain about their perception at stimulus intensities where participants more frequently report PHS, reflected in longer response times and lower confidence ratings. Thus for the unsure perceiver we map the probability of responding PHS directly to the response times and confidence ratings through affine functions.

Both true and unsure perceiver models response times and confidence ratings were estimated with the addition of thermal contrast as a regressor, in order to disentangle the contribution of the reporting of PHS from the thermal contrast itself (see Supplementary Materials for a full set of equations and description of the full models).


### Model Estimation and Selection

All models were fitted using Stan’s Hamiltonian Markov chain Monte Carlo No U-turn sampler [@team_stan_nodate]. To ensure that all models fit our defined diagnostic criteria, we increased the target average acceptance probability from .95 to .99 and the maximum tree depth from 12 to 15 to ensure no divergent transitions, as outlined in the contingency plans of the pre-registered analyses. We also increased the number of warm-up and post warm-up samples from 1,000 to 2,000 for each of the four chains to ensure R-hat values below 1.01 and effective sample size above 400 diagnostic values. Further, we inspected trace and pair plots to investigate sampling of the parameter space. We specified hyperpriors based on simulated data and prior knowledge [@mitchell_thermal_2024].

Model selection was conducted using approximate leave-one-out cross-validation, as implemented in the loo package [@vehtari_practical_2017]. We initially applied Pareto smoothed importance sampling leave-trial-out cross-validation. However, both models had Pareto-k’s (diagnostic measure) exceeding 0.7, (`r round(sum(loo_models[[1]]$diagnostics$pareto_k>0.7) / length(loo_models[[1]]$diagnostics$pareto_k) * 100, 2)`%) and (`r round(sum(loo_models[[2]]$diagnostics$pareto_k>0.7) / length(loo_models[[2]]$diagnostics$pareto_k) * 100 , 2)`%) for the true perceiver and unsure perceiver model, respectively. In an attempt to address this, we switched to moment matching importance sampling leave-trial-out cross-validation, but the same trials remained problematic. Model performance was evaluated using ELPD, with higher values indicating better ability to explain the data.

We tested the two multivariate models through parameter recovery to ensure both could accurately recover their generating parameters, and also performed model recovery to ensure discriminability between the two generative models. We further used these simulations to investigate the feasibility of including an age regressor on both threshold and slope of the psychometric function, which revealed that we were only able to detect a difference in the threshold given the assumed effect sizes. Full details are documented in the pre-registration and Fig. S6.
