%% Instructions for phs_contrast_main.m in English
% Adapted from: AG Mitchell, JF Ehmsen, DE Christensen
% 23.06.22

% By AG Mitchell
% Last edited: 23.01.2024

%% Instructions
vars.display.actStart = ['Først vil du mærke termoden skifte temperatur ',...
    'efter et øjeblik, vil du høre en tone.\n\n',...
    'Din opgave et at trykke på OP PILETASTEN når du føler hvilken som helst ændring i fornemmelsen fra det æjeblik du hørte tonen \n\n',...
    'Derefter skal du svare på to spørgsmål: \n\n',...
    '(1) Hvilken temperatur følte du? VARM eller KOLD \n\n',...
    '(2) Hvor sikker var du på din rapporterede fornemmelse?? Fra 0 (Gæt) til 100 (Sikker) \n\n',...   
    'Du skal besvare hvert spørgsmål med venstre og højre piletaster. \n',...
    'I Spørgsmål nummer 2 skal du bekræfte dit svar på bedømmelsesskalaen ved at trykke på OP piletasten. \n\n',....
    'Du vil nu have muligheden for at øve dig på opgaven.. \n\n',...
    'Tryk på en vilkårlig tast for at fortsætte'];

vars.display.restart = 'Fortsætter eksperimentet...';
vars.display.pause = 'Du kan nu tage en kort pause.. \n\n Tryk på en tast, når du er klar til at fortsætte eksperimentet.';
vars.display.changeArms = 'Placer venligst termoden på din anden arm. Tryk på en tast for at starte.';
vars.display.starting = 'Starter næste blok...';
vars.display.pressButtonText = 'Efter tonen skal du trykke på OP piletasten, når du føler en ændring.';

vars.display.mainExperiment = ['Nu starter det egentlige eksperiment.. \n\n', ...
    'Hvis du føler, at du har brug for at gentage øvelsesrunden, så kontakt venligst personalet.\n\n ', ...
    'Ellers skal du trykke på en vilkårlig tast for at fortsætte.'];

%% FC response
vars.display.question = {'Da du trykkede på knappen, hvilken temperatur følte du?',...
                         'Da du trykkede på knappen, føltes stimulusen brændende?',...
                         ['I runder, hvor temperaturændringen ikke var umiddelbart tydelig \n',... 
                         'var du mere tilbøjelig til at trykke på en knap i det øjeblik, du opdagede ændringen, selvom du ikke var sikker, \n',...
                         'eller var du mere tilbøjelig til at vente, indtil du var sikker på temperaturkvaliteten?']};
 
                     
vars.display.questionCode = [1 2]; % as list: 1 - burn, 2 - temperature, 3 - VAS
vars.display.whichQuestion = [1 0]; %Enable or disable question (1 = enabled) %% not sure this works, needs fixing!

vars.display.whichKey = {'LR', 'UD'}; % Left/Right. Up/Down. If you are using the mouse as an input device let this entirely as LR 

vars.display.feedback ={'Kold' 'Varm';...
                        'Ja' 'Nej';...
                        'Trykkede mens jeg var usikker' 'Ventede til jeg var sikker'}; %First Feedback for 1. Then for 0.

%% VAS ratings
vars.display.StartVas = ['Når instrueret af personalet, skal du trykke på en tast for at starte vurderingen..\n\n' ...
    'Når du er færdig, skal du trykke på mellemrum for at gå videre til næste skala..'];

vars.display.ConfEndPoints = [{'Gæt', 'Sikker'};...
                              {'Aldrig', 'Altid'}; ...
                              {'Aldrig', 'Altid'}];   

vars.display.VASquestion = [{'Hvor sikker var du på din rapporterede fornemmelse?'}, ...
    {'Når du var usikker på temperaturændringen, hvor ofte trykkede du på knappen alligevel?'}, ...
    {'Hvor ofte ventede du med at trykke på en knap, indtil du var sikker på, om temperaturændringen var varm eller kold?'}]; 

% Task performance check
vars.display.perfCheckinstr = ['Før vi afslutter, vil vi gerne spørge dig, hvordan du gik til opgaven. \n\n',...
    'Først vil vi spørge dig, hvilken metode du var mest tilbøjelig til at bruge, hvilket du kan vælge ved at bruge venstre og højre piletaster. \n',...
    'Derefter vil vi bede dig om at vurdere, hvor ofte du brugte hver metode på to vurderingsskalaer. \n\n',...
    'Tryk på en vilkårlig tast for at fortsætte.'];

                                   
                                   