%% Instructions for phs_contrast_main.m in English
% Adapted from: AG Mitchell, JF Ehmsen, DE Christensen
% 23.06.22

% By AG Mitchell
% Last edited: 23.01.2024

%% Instructions
vars.display.actStart = ['First, you will feel the thermode change temperature ',...
    'and after a short time, you will hear a tone.\n\n',...
    'Your task is to press the UP ARROW when you feel any change in sensation from the point at which you heard the tone \n\n',...
    'After, you will have to answer two questions: \n\n',...
    '(1) Which temperature did you feel? WARM or COLD \n\n',...
    '(2) How confident were you in your reported sensation? From 0 (Guess) to 100 (Certain) \n\n',...   
    'You will answer each question with the LEFT and RIGHT arrow keys \n',...
    'For the second question, you can confirm your response on the rating scale by pressing the UP arrow \n\n',...
    'You will now have an opportunity to practice the task \n\n',...
    'To continue, please press any key'];

vars.display.restart = 'Continuing the experiment...';
vars.display.pause = 'You can now take a short break. \n\n Press a key when you are ready to continue the experiment.';
vars.display.changeArms = 'Please place the thermode on your other arm. Press a key to start';
vars.display.starting = 'Starting the next block...';
vars.display.pressButtonText = 'After the tone, press the UP arrow when you feel a change';

vars.display.mainExperiment = ['You will now start the main experiment. \n\n', ...
    'If you feel you need to repeat the pratice, please let the experimenter know. \n\n', ...
    'Otherwise, press any key to continue'];

%% FC response
vars.display.question = {'When you pressed the button which temperature did you feel?',...
                         'When you pressed the button did the stimulus burn?',...
                         ['For trials where the temperature change was not immediately obvious \n',... 
                         'were you more likely to press a button the moment you detected the change, even though you were not sure, \n',...
                         'or were you more likely to wait until you were sure of the temperature quality?']};
 
                     
vars.display.questionCode = [1 2]; % as list: 1 - burn, 2 - temperature, 3 - VAS
vars.display.whichQuestion = [1 0]; %Enable or disable question (1 = enabled) %% not sure this works, needs fixing!

vars.display.whichKey = {'LR', 'UD'}; % Left/Right. Up/Down. If you are using the mouse as an input device let this entirely as LR 

if mod(str2double(vars.control.ID),2) == 0 %if subject number is even
    vars.display.feedback ={'Warm' 'Cold';...
                            'Yes' 'No';...
                            'Press when not sure' 'Wait until sure'}; %First Feedback for 1. Then for 0.
else %if subject number is odd
    vars.display.feedback ={'Cold' 'Warm';...
                            'Yes' 'No';...
                            'Press when not sure' 'Wait until sure'}; %First Feedback for 1. Then for 0.
end

%% VAS ratings
vars.display.StartVas = ['When instructed by the experimenter, press a key to start rating.\n\n' ...
    'Once done, press SPACE to move to the next scale.'];

vars.display.ConfEndPoints = [{'Guess', 'Certain'};...
                              {'Never', 'Always'}; ...
                              {'Never', 'Always'}];   

vars.display.VASquestion = [{'How confident were you in your reported sensation?'}, ...
    {'When you were unsure about the temperature change, how often did you press the button regardless?'}, ...
    {'How often did you wait to press a button until you were sure of that the temperature change was warm or cold?'}]; 

% Task performance check
vars.display.perfCheckinstr = ['Before we finish, we would like to ask you how you performed the task. \n\n',...
    'First, we will ask you which method you were more likely to use,\n which you can select using the left and right arrow keys. \n',...
    'Then we will ask you to rate how often you used each method, on two ratings scales. \n\n',...
    'Press any key to continue'];

                                   
                                   