---
title: "PHS ageing study"
author: "Alexandra G. Mitchell, Jesper F. Ehmsen, Camilla E. Krænge & Francesca Fardo"
date: "11/07/2024"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Load required packages
if (!require("pacman")) install.packages("pacman")
  pacman::p_load(ggplot2, reshape2, tidyverse)
```

# Define key variables
```{r}
# where the data is
projPath = '/mnt/slow_scratch/ageing-and-neuropathy'
datPath <- file.path(projPath, 'data')

session = 'ses-01'

# where the analysis is
gitPath = '/home/alexm/Git/phs-ageing'
anaPath = file.path(gitPath, 'analysis')
```

# find and load all .tsv results files
```{r}
# identify subject folders - all participants
subs = dir(datPath, pattern = 'sub-([1-5])')

# loop through and extract relevant data
c1 = 0
for (s in subs) {
  c1 = c1 + 1 #counter
  
  sPath = file.path(datPath, s, session, 'beh', 'phs_con')
  datFiles = list.files(sPath, pattern = 'phs_con_beh_results')
  
  # only compile if the file exists
  if(file.exists(file.path(sPath, datFiles[1]))){
    dat = read.delim(file.path(sPath, datFiles[1]), sep = '\t')
  
    # make large data-frame
    if (c1 == 1){
      allDat = dat
    } else {
      allDat = rbind(allDat, dat)
    }
  }
  
}
```

```{r}
# find and replace the badly entered ID (1++9)
# load demographics and merge
demoFile <- list.files(projPath, '\\.csv$')
demo <- read.delim(file.path(projPath, demoFile[2]), sep=',')
# create subject column to merge data-frames
demo <- demo %>%
  group_by(ID) %>%
  mutate(subject = paste0("sub-", ID)) %>%
  ungroup()
# merge
allDat1 <- allDat %>% 
  left_join(demo, by = 'subject') %>%
  filter(include_phs == 1) %>% 
  mutate(group = substr(subject, 5, 5)) %>% 
  select(-c('ID'))

pat <- allDat1 %>% 
  filter(group == 5) %>% 
  mutate(patient = 1)

hc <- allDat1 %>% 
  filter(group < 5) %>% 
  filter(age > 46) %>% 
  mutate(patient = 0)

patDat <- rbind(pat,hc)

# remove the one participant where t2 is above t3 & t4
temps <- patDat %>% group_by(subject, temp_cond) %>% 
  summarise(tmax = mean(tmax_temp)) %>% 
  pivot_wider(names_from = 'temp_cond', values_from = 'tmax') %>% 
  rename('t1' = '1',
         't2' = '2',
         't3' = '3',
         't4' = '4') %>% 
  mutate(flag = ifelse(t2 > t3, 1, 0))

flagID <- temps %>% 
  filter(flag == 1)

# identify flagged id
patDat <- patDat %>% filter(!(subject %in% flagID$subject)) #Gives us the initial dataset minus people with an MNSI score >= 7, however none of 

# finally, save compiled data-frame
write.csv(patDat, file.path(gitPath, 'data', 'phs-patients_compiled-data.csv'), row.names = FALSE)
```

```{r}

```

